// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSvgX99uxSew3JjfRHBuzoKk_IEE6eRNA',
    appId: '1:1057783779334:web:868465fe38b50e838f7387',
    messagingSenderId: '1057783779334',
    projectId: 'grocery-flutter-course-f7e3d',
    authDomain: 'grocery-flutter-course-f7e3d.firebaseapp.com',
    storageBucket: 'grocery-flutter-course-f7e3d.appspot.com',
    measurementId: 'G-N3EB8M770Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLxnYd8CZlNvk-ZdastglW7rHKzm7yB2k',
    appId: '1:1057783779334:android:8a6adf1b45bf8e528f7387',
    messagingSenderId: '1057783779334',
    projectId: 'grocery-flutter-course-f7e3d',
    storageBucket: 'grocery-flutter-course-f7e3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8wl5zkZfyOE6_P2ewCX4dXOm67ZrgzJc',
    appId: '1:1057783779334:ios:97acde40322da0248f7387',
    messagingSenderId: '1057783779334',
    projectId: 'grocery-flutter-course-f7e3d',
    storageBucket: 'grocery-flutter-course-f7e3d.appspot.com',
    androidClientId: '1057783779334-71ug5im7b7sa7cqrejul8ca50cq4m05l.apps.googleusercontent.com',
    iosClientId: '1057783779334-1dtcp7ki5b153desibq8u6nlv82j43fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryWebAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8wl5zkZfyOE6_P2ewCX4dXOm67ZrgzJc',
    appId: '1:1057783779334:ios:97acde40322da0248f7387',
    messagingSenderId: '1057783779334',
    projectId: 'grocery-flutter-course-f7e3d',
    storageBucket: 'grocery-flutter-course-f7e3d.appspot.com',
    androidClientId: '1057783779334-71ug5im7b7sa7cqrejul8ca50cq4m05l.apps.googleusercontent.com',
    iosClientId: '1057783779334-1dtcp7ki5b153desibq8u6nlv82j43fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryWebAdmin',
  );
}
